definitions:
  200Flights:
    type: array
    example:
      - id: 34
        priceUsd: 99
        tripClassName: "Economy"
        origin: "TJM"
        destination: "LED"
        departureDate: "2023-05-30T06:00:00.000Z"
        md5Hash: "41181a138b1eb1eb4c65ba235c370df4"
        returnDate: "2023-06-03T06:00:00.000Z"
        duration: 395
        distance: 2032
      - id: 36
        priceUsd: 99
        tripClassName: "Economy"
        origin: "AER"
        destination: "KZN"
        departureDate: "2023-05-31T06:00:00.000Z"
        md5Hash: "dace37826a41d255df231d5a0ae350cf"
        returnDate: "2023-06-04T06:00:00.000Z"
        duration: 440
        distance: 1508
  500Flights:
    type: string
    example: "There was an error with your request"
  200FlightIngest:
    type: string
    example: "Ingest successful"
/flights:
  get:
    description: GET flights
    responses:
        200:
          description: Returns all flights in database
          schema:
            $ref: '#/definitions/200Flights'
        500:
          description: Error returned if catastrophic error occurs, like database conneciton breaks
          schema:
            $ref: '#/definitions/500Flights'
/jobs/flightsingest:
  post:
    description: Kick off flight ingest job
    responses:
      200:
        description: Returns a 200 if ingest completes successfully
        schema:
          $ref: '#/definitions/200FlightIngest'
      422:
        description: Returns a 422 if one or more incoming flights was malformed and not ingested
      500:
        description: Error returned if catastrophic error occurs, like database conneciton breaks
      502:
        description: Indicates an error with the source API fetch call
      